### ISSUE TITLE
Does not detect the tasks from a devcontainer

### ISSUE THREAD

**Issue by gmolveau** [iulianraduat/vscode-tasks-sidebar#3]
I'm using a vscode devcontainer for my project. The extension works for the tasks in the `.vscode/tasks.json` file but does not find the tasks in `.devcontainer/devcontainer.json` file.

**Comment by iulianraduat** [comment]
Hi @gmolveau,

This extension displays what is made available by VSCode API so if your tasks are not there then I cannot help you. Maybe an update in the future of the API will also  detect these tasks.

Cheers,
Iulian
